---
Name: catalogroutes
After: framework/routes#rootroutes
---
Director:
  rules:
    'cart/$Action/$ID/$Quantity': 'Cart_Controller'
    'checkout/$Action/$ID': 'Checkout_Controller'
    'payment/$Action/$ID': 'Payment_Controller'
---
Name: modelascontrollerroutes
After: cms/routes#modelascontrollerroutes
---
Director:
  rules:
    '': 'RootURLController'
    '$URLSegment//$Action/$ID/$OtherID': 'CommerceURLController'
